blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}/discussions
    about: Ask questions, share ideas, and connect with the community
  - name: 📚 Documentation
    url: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}/blob/main/README.md
    about: Check out our documentation for guides and API references
  - name: 🚀 Roadmap
    url: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}/projects
    about: See what we're working on and what's planned for the future
  - name: 🔒 Private Security Report
    url: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}/security/advisories/new
    about: Report sensitive security vulnerabilities privately
